### ISSUE TITLE
File paths

### ISSUE THREAD

**Issue by SkipTyler** [dvlden/webpack-config#2]
Hey, @dvlden! 
I have a problem with the build.

It does not correctly prescribe ways.
For example.
```
<script type="text/javascript" src="/scripts/app.js">
<link href="/styles/app.css" rel="stylesheet">
,url(/fonts/OpenSans-Regular.ttf)
background-image:url(/images/form_bg.png)

```
But it loads everything, if the paths are written so
```

<script type="text/javascript" src="scripts/app.js">
<link href="styles/app.css" rel="stylesheet">
,url(fonts/OpenSans-Regular.ttf) format("truetype")
background-image:url('../images/form_bg.png');

```

I did not make changes to the config

**Comment by nnx0r** [comment]
Hey @SkipTyler !
I am aware of that little issue. Had to use sub-directories a couple of times for some clients and I needed to manually change those paths after build, in order to make it work.

I have fixed this actually, but I forgot to push new version, which I'll do sometime later...

However, it'll work fine if you are building your project locally and it will end up in the root directory of a domain in production...

So it will work properly in these two cases:

1. `yarn dev` or `npm run dev`- which will run the server (e.g. `localhost:8080`)
2. `yarn build`  or `npm run build` - which will make it ready for production and you upload the site to the root path of domain (e.g. `domain.com`) no sub-dirs...

**Comment by nnx0r** [comment]
Give me a moment to push an update which resolves those issues for me.

**Comment by nnx0r** [comment]
This should be fixed now in new commit. Can you please try it out?

**Comment by SkipTyler** [comment]
This solved the problem with paths in the css
For fonts and images

css and js is still connected in the old way

**Comment by nnx0r** [comment]
That's interesting 😩 

I just used an old project with assets to test it and it injects proper and updated paths...

```html
<!-- Styles before enclosing HEAD tag -->
<link href="styles/vendor.css" rel="stylesheet" integrity="sha384-60QNtHgQGpg28vH/uhwlwDKckHNUspugA44nmGc3MGtQ1f01ulLnYBWhh84d1+nd" crossorigin="anonymous">

<link href="styles/app.css" rel="stylesheet" integrity="sha384-fGn/sANBjvasZJhCFjKoj50czK03L/7RvojfKyjgkSu5PimQcVkb2xf5pCTTp072" crossorigin="anonymous">

<!-- Scripts before enclosing BODY tag -->
<script src="scripts/vendor.js" integrity="sha384-TI2qNirdmrbk6nGIUGfNIb4Nnj+SR8pAHNyyiNclR82oZO+Iri1EfLrMdPSIyDTA" crossorigin="anonymous"></script>

<script src="scripts/app.js" integrity="sha384-aqlIE9OAanqnA7J4o6+D5UOtwoPB09/jHFjyxDMcIIGF2WIPjeZz+dwKxe86UF28" crossorigin="anonymous"></script>
```

> Notice the paths... They are not absolute anymore.

**Comment by nnx0r** [comment]
@SkipTyler There you go... I noticed one line having incorrect path, so now it is all good.
Enjoy!

**Comment by SkipTyler** [comment]
@dvlden Working! Thank you so much!

**Comment by nnx0r** [comment]
@SkipTyler - I'm glad it worked out for you too. Thank you for your interest in using my config or learning from it. Either way, I'm happy I was able to help.
